### ISSUE TITLE
Can you please upload the Godot project?

### ISSUE THREAD

**Issue by shujaatak** [th28/godot2dtut-csharp#1]

**Comment by th28** [comment]
Sure. I actually lost the original project files (moving between computers) but should be easy enough to recreate since I have the code. I'll try to have it up before the weekend.

**Comment by th28** [comment]
Added the full src directory (previously the level scene was missing). All scenes plus sample assets can be found in the assets folder. Hopefully this is what you need.

**Comment by shujaatak** [comment]
Thank you so much @th28 !
